### ISSUE TITLE
Namespace naming conflicts and inconsistency

### ISSUE THREAD

**Issue by cathrinevaage** [zajrik/discord.js-typings#52]
The namespace used, `'discord.js'`, is somewhat troublesome.

There is no way to represent the namespace name used in jsdoc.
The dot suggest there is a sub namespace, discord > js, and you can't put quotes around it.

Also, in the documentation for discord.js, it's always imported as `Discord`, thus it would make sense that the namespace is called `Discord`.

**Comment by evaera** [comment]
This is a problem for me too. Did you find a solution, @Jovaage?

**Comment by cathrinevaage** [comment]
Sadly, no.

**Comment by zajrik** [comment]
The problem here is if we change the name of the declared module, the typings no longer map to the package itself. Open up index.d.ts in the typings yourself, change it to `declare module 'Discord'` and try to build. You will no longer have access to the Discord.js typings and your build will throw errors.

Yes, in a TypeScript environment we would not declare namespaces in such a way, but regrettably this is not a native TypeScript project, We are providing support for a JavaScript package, and have to make certain accommodations. You are not limited in your own code by what the module is declared as.

As far as JSDoc is concerned, it has no concept of TypeScript integrations. Whatever this module is declared as has no bearing on how you choose to document things related to this package. Or at least it shouldn't. Without seeing specific examples I can't offer any advice on the matter.

**Comment by evaera** [comment]
In my case, I was using the JSDoc comments to [type check normal JavaScript](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files) with the TypeScript checker, but I didn't have access to any of discord.js's types without importing them. It looks like the types that are annotated in JSDoc aren't allowed to use types that exist elsewhere in the project in TypeScript files. There's an [open issue](https://github.com/Microsoft/TypeScript/issues/14377) proposing a way to import types from other files in JSDoc that would fix this problem, but looks like there's no good solution right now.

After all of that nonsense, I just decided to switch my project to TypeScript and be done with it. :P

**Comment by zajrik** [comment]
Admittedly I hadn't considered JavaScript type checking via JSDoc annotations. As an explicit TS user, I had forgotten that was a thing. But yes, our goal is to support TypeScript, and actually using TS itself is a far better choice than the JavaScript type checking, in my opinion at least. I do understand how frustrating it can be to do a full migration, though. My framework was originally in JS and it was definitely no small task to migrate fully to TS.

If you have any questions related to getting started with TS feel free to contact me on Discord.
