### ISSUE TITLE
Cannot get typings to load

### ISSUE THREAD

**Issue by ryanagillie** [zajrik/discord.js-typings#64]
Hello, recently converted to TS with my discord bot. I'm having an issue where I can't get any of the discord.js typings to load at all. 

Here is my tsconfig
![07ae174df9ae7b553a95a654ade338e2](https://user-images.githubusercontent.com/35985028/39842581-ef7375c6-53b4-11e8-9e9b-f7b15c8b5846.png)

Here is my package.json
![d33872f771f75fb2d668405476033958](https://user-images.githubusercontent.com/35985028/39842414-553c0770-53b4-11e8-9df2-fb3ca30a2736.png)

and here is an example of it not working
![unknown](https://user-images.githubusercontent.com/35985028/39842515-9b51ab52-53b4-11e8-9156-f4c21d74b7f5.png)

**Comment by SpaceEEC** [comment]
I can not reproduce that linter/editor(?) warning/error you have.

After cloning the repo, assuming [RITesports/ricky](https://github.com/RITesports/ricky) is the correct one, I installed deps `npm i `, and successfully ran `npx tslint -p ./` and `npx tsc -p ./` without receiving any errors or warnings.

VSCode Insiders wasn't reporting any errors for me as well after specifying the types of the event, like you did in your screenshot:
![image](https://user-images.githubusercontent.com/24881032/39870424-9fea414e-5461-11e8-85f7-e04c9e6ad99b.png)

Since you are importing Discord as `import * as Discord from 'discord.js';` that shouldn't actually happen.

**Comment by ryanagillie** [comment]
I’m sorry, I fixed the issue last night after writing this and I forgot to close it. My issue was I was requiring discord.js and not importing it. Thank you so much for the response though!
