### ISSUE TITLE
Use interfaces instead of type aliases

### ISSUE THREAD

**Issue by seangenabe** [zajrik/discord.js-typings#67]
I've noticed that this repo uses mostly type aliases.

The TypeScript documentation recommends [using interfaces over type aliases if possible](https://www.typescriptlang.org/docs/handbook/advanced-types.html#interfaces-vs-type-aliases). For example, `TextBasedChannelFields` should probably be:

```typescript
interface TextBasedChannelFields extends PartialTextBasedChannelFields {
  typing: boolean;
  // other fields...
}
```

**Comment by xDamon** [comment]
I guess you could just make a pr if you really care about it. The TypeScript documentation is pretty outdated and the reasons they have listed there are not really true anymore.

Edit: Just to elaborate, type aliases do show up in errors, they can be implemented just like interfaces and they can be "extended" with intersections.

**Comment by zajrik** [comment]
That's not entirely true in this case. Having a name that can be referred to rather than an object literal in cases of a passed value not meeting the shape of the required type can mean a huge difference in compiler error legibility.

Additionally, I personally prefer to strictly use interfaces for things that will actually be implemented, but I'm becoming more open to using interfaces for other purposes in my own code lately.

That said, this is a case for a PR rather than an issue. I can tell you now I don't want to have to go back over all the work I've put into this and convert types to interfaces. 

If you want to prepare your own PR for this you're more than welcome to. I'm not going to leave this issue open in the meantime because it's far from pertinent and I don't foresee anyone else on the team wanting to take the time to tackle this either.
